AgroSocial/config/routes.rb
AgroSocial::Application.routes.draw do

  devise_for :users
  devise_for :associations
  
  resources :events, :shallow => true do
    resources :notices
  end

  resources :feeds

  root :to => "home#index"

  

end

AgroSocial/app/models/notice.rb
class Notice < ActiveRecord::Base



	#attributes#
  	attr_accessible :author, :content, :date, :title
  	
	#references#
	belongs_to :event

	def self.getNoticesN(n)
		 Notice.find(:all, :order => "date_time", :limit => n).reverse
	end

end

AgroSocial/app/controllers/notices_controller.rb
class NoticesController < ApplicationController
  before_action :set_notice, only: [:show, :edit, :update, :destroy]


  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, :alert => exception.message
  end

  # GET /notices
  # GET /notices.json
  def index
    @notices = Notice.all
  end

  # GET /notices/1
  # GET /notices/1.json
  def show
  end

  # GET /notices/new
  def new
    @notice = Notice.new
    @event = Event.find(params[:event_id])
  end

  # GET /notices/1/edit
  def edit
    #Authorizations
    event = Event.find(:event_id)
    authorize! [:edit], event
  end

  # POST /notices
  # POST /notices.json
  def create
    event = Event.find(params[:event_id])
    authorize! [:edit], event

    @notice = Notice.new(notice_params)
    @notice.event_id = params[:event_id]

    respond_to do |format|
      if @notice.save
        format.html { redirect_to @notice, notice: 'Notice was successfully created.' }
        format.json { render action: 'show', status: :created, location: @notice }
      else
        format.html { render action: 'new' }
        format.json { render json: @notice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notices/1
  # PATCH/PUT /notices/1.json
  def update
    #Authorizations
    event = Event.find(params[:event_id])
    authorize! [:edit], event
    
    respond_to do |format|
      if @notice.update(notice_params)
        format.html { redirect_to @notice, notice: 'Notice was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @notice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notices/1
  # DELETE /notices/1.json
  def destroy
    #Authorizations
    event = Event.find(Notice.find(params[:id]).event_id)
    authorize! [:edit], event


    @notice.destroy
    respond_to do |format|
      format.html { redirect_to notices_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notice
      @notice = Notice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def notice_params
      params.require(:notice).permit(:title, :date_time, :content, :author)
    end
end

AgroSocial/app/helpers/notices_helper.rb
module NoticesHelper
end

AgroSocial/app/views/notices/_form.html.erb
<%= form_for([@event, @notice]) do |f| %>
  <% if @notice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@notice.errors.count, "error") %> prohibited this notice from being saved:</h2>

      <ul>
      <% @notice.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :date_time %><br>
    <%= f.date_select :date_time %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

AgroSocial/app/views/notices/edit.html.erb
<h1>Editing notice</h1>

<%= render 'form' %>

<%= link_to 'Show', @notice %> |
<%= link_to 'Back', notices_path %>

AgroSocial/app/views/notices/index.html.erb
<h1>Listing notices</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Date time</th>
      <th>Content</th>
      <th>Author</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @notices.each do |notice| %>
      <tr>
        <td><%= notice.title %></td>
        <td><%= notice.date_time %></td>
        <td><%= notice.content %></td>
        <td><%= notice.author %></td>
        <td><%= link_to 'Show', notice %></td>
        <td><%= link_to 'Edit', edit_notice_path(notice) %></td>
        <td><%= link_to 'Destroy', notice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Notice', new_notice_path %>

AgroSocial/app/views/notices/new.html.erb
<h1>New notice</h1>

<%= render 'form' %>

<%= link_to 'Back', event_notices_path %>

AgroSocial/app/views/notices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @notice.title %>
</p>

<p>
  <strong>Date time:</strong>
  <%= @notice.date_time %>
</p>

<p>
  <strong>Content:</strong>
  <%= @notice.content %>
</p>

<p>
  <strong>Author:</strong>
  <%= @notice.author %>
</p>

<%= link_to 'Edit', edit_notice_path(@notice) %> |
<%= link_to 'Back', events_path(@event) %>